import { describe, it, expect, vi } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { checkClaims, extractClaims, guardSuggestion, guardSummary, markInline, unverifiedNote, type ClaimMaterial } from "../claim-guard";

const STATS = "New signups (7d): 0\nTotal users: 19\nMatches created (7d): 2\nTotal teams: 6\nBehavior reports (total): 2\nNotifications sent (7d): 14";
const mat = (data: string[] = [STATS], context: string[] = []): ClaimMaterial => ({ data, context });
const unv = (text: string, m: ClaimMaterial = mat()) => checkClaims(text, m).unverified.map((c) => c.raw);

describe("verified figures", () => {
  it("1. exact supplied integers", () => {
    expect(unv("There are 19 users and 6 teams; only 2 matches were created in the last 7 days.")).toEqual([]);
  });
  it("2. exact supplied decimals", () => {
    expect(unv("Average rating is 1482.5 across teams.", mat(['[{"avg_rating":1482.5}]']))).toEqual([]);
  });
  it("3. exact supplied percentages (as percent or fraction)", () => {
    expect(unv("Retention is 42.5%.", mat(["retention: 42.5%"]))).toEqual([]);
    expect(unv("Retention is 42.5%.", mat(['[{"retention":0.425}]']))).toEqual([]);
  });
  it("4/5. simple derived percentages and ratios from tool data (2/19)", () => {
    expect(unv("Only 2 of 19 users (10.5%) created a match.")).toEqual([]);
    expect(unv("That is about 11% of users.")).toEqual([]);
    expect(unv("Teams average 3.17 users.")).toEqual([]); // 19/6
  });
  it("numbers from the input message / system prompt count (exact only)", () => {
    expect(unv("As noted, the app has 16 users in Cyprus.", mat([], ["pre-revenue at 16 users"]))).toEqual([]);
  });
});

describe("unverified figures", () => {
  it("6. the smoke-test '6% engagement' is flagged", () => {
    expect(unv("Only 2 matches created and just 6% engagement via behavior reports.")).toEqual(["6%"]);
  });
  it("7. unsupported counts are flagged", () => {
    expect(unv("We lost 47 active players this week.")).toEqual(["47"]);
  });
  it("8. unsupported currency amounts are flagged", () => {
    expect(unv("Courts generated €1,200 in bookings.")).toEqual(["€1,200"]);
    expect(unv("That is $350 of revenue.")).toEqual(["$350"]);
  });
  it("9. unsupported dates and measurements are flagged", () => {
    expect(unv("The drop started on 2026-08-14.")).toEqual(["2026-08-14"]);
    expect(unv("The home screen takes 850ms to load.")).toEqual(["850ms"]);
    expect(unv("Match creation takes 3.5 minutes on average.")).toEqual(["3.5 minutes"]);
  });
  it("percentages are not derived from context-only numbers", () => {
    expect(unv("That is 50% growth.", mat([], ["3 sharp findings beat 6 generic ones"]))).toEqual(["50%"]);
  });
  it("integers are never 'derived' by arithmetic", () => {
    expect(unv("We have 21 accounts.")).toEqual(["21"]); // 19 + 2 is not accepted
  });
  it("a number already marked [unverified] never counts as support", () => {
    expect(unv("Engagement is 6%.", mat([STATS], ["Your earlier conclusion: 6% [unverified] engagement"]))).toEqual(["6%"]);
  });
});

describe("false-positive avoidance", () => {
  it("10. hypothetical / example / target numbers are not treated as factual claims", () => {
    expect(unv("If conversion is <2%, the signup flow needs fixing; if it's >15%, traffic is too low.")).toEqual([]);
    expect(unv("Target: 30% of new users play a first match within 7 days.")).toEqual([]);
    expect(unv("Expected lift: 20% more matches.")).toEqual([]);
    expect(unv("For example, 50 users could join via a court partner.")).toEqual([]);
    expect(unv("e.g. 12 teams per league would work.")).toEqual([]);
  });
  it("11. model/version/tool identifiers, ids, paths, code and timestamps are ignored", () => {
    const t =
      "Generated by ollama/qwen3.5:4b and gemini/gemini-3.8-flash (also gemini-3.1-flash-lite, v2, 1.2.3). " +
      "See lib/match_repository.dart:42 and `select count(*) from t limit 50`. Row 3f2b8c1e ran at 2026-09-26T12:00:00Z. " +
      "Using OAuth2 and ES2017 on Phase 1.";
    expect(extractClaims(t)).toEqual([]);
  });
  it("list markers and bare years are ignored", () => {
    expect(extractClaims("1. Fix onboarding\n2) Add reminders\nPlanned for 2027.")).toEqual([]);
  });
});

describe("annotation helpers", () => {
  it("marks inline and builds a note", () => {
    const { unverified } = checkClaims("just 6% engagement and 47 players", mat());
    expect(markInline("just 6% engagement and 47 players", unverified)).toBe("just 6% [unverified] engagement and 47 [unverified] players");
    expect(unverifiedNote(unverified)).toBe("⚠ Unverified figures (not found in or derivable from this cycle's data): 6%, 47");
    expect(unverifiedNote([])).toBe("");
  });

  it("12/17. guardSuggestion: provenance for any provider/model; inline marks + note only when needed", () => {
    const clean = guardSuggestion({ title: "Only 2 matches", body: "19 users, 2 matches.", evidence: "read_footrank_stats" }, mat(), "gemini/gemini-3.5-flash-lite");
    expect(clean).toMatchObject({ title: "Only 2 matches", body: "19 users, 2 matches.", footer: "Generated by gemini/gemini-3.5-flash-lite", unverified: [] });
    const bad = guardSuggestion({ title: "Engagement at 6%", body: "19 users; 6% engagement.", evidence: "stats: 6% engaged" }, mat(), "ollama/qwen3.5:4b");
    expect(bad.title).toBe("Engagement at 6% [unverified]");
    expect(bad.body).toBe("19 users; 6% [unverified] engagement.");
    expect(bad.evidence).toBe("stats: 6% [unverified] engaged");
    expect(bad.footer).toBe("⚠ Unverified figures (not found in or derivable from this cycle's data): 6%\nGenerated by ollama/qwen3.5:4b");
    expect(bad.unverified).toEqual(["6%"]);
  });

  it("15. guardSummary annotates unsupported figures so memory can't replay them as fact", () => {
    const smoke =
      "The smoke test data reveals a critical funnel leak: zero new signups in 7 days despite 19 existing users generating minimal activity (only 2 matches created and just 6% engagement via behavior reports).";
    const g = guardSummary(smoke, mat());
    expect(g.unverified).toEqual(["6%"]);
    expect(g.text.startsWith("[⚠ figures marked [unverified] were not in this cycle's data] ")).toBe(true);
    expect(g.text).toContain("just 6% [unverified] engagement");
    expect(g.text).toContain("19 existing users"); // useful, verified content preserved
  });

  it("16. a fully verified summary is stored unchanged", () => {
    const s = "19 users, 6 teams, and only 2 matches in 7 days; 0 new signups (10.5% of users played).";
    expect(guardSummary(s, mat())).toEqual({ text: s, unverified: [] });
  });
});

describe("18. no network, no LLM", () => {
  it("the guard never calls fetch and imports nothing", () => {
    const f = vi.fn();
    vi.stubGlobal("fetch", f);
    guardSummary("6% engagement from 47 players", mat());
    guardSuggestion({ title: "x 5%", body: "y", evidence: "" }, mat(), "ollama/qwen3.5:4b");
    expect(f).not.toHaveBeenCalled();
    vi.unstubAllGlobals();
    const src = readFileSync(join(__dirname, "..", "claim-guard.ts"), "utf8");
    expect(src).not.toMatch(/^\s*import\s/m);
    expect(src).not.toMatch(/fetch\(|free-llm|process\.env/);
  });
});
