import { describe, it, expect, vi, beforeEach } from "vitest";

const { saveSuggestion, notify } = vi.hoisted(() => ({ saveSuggestion: vi.fn(), notify: vi.fn() }));
vi.mock("../../lib/suggestions", () => ({ saveSuggestion: (...a: unknown[]) => saveSuggestion(...a) }));
vi.mock("../../lib/notify", () => ({ notify: (...a: unknown[]) => notify(...a) }));
vi.mock("../../lib/supabase", () => ({ supabaseAdmin: {} }));

import { dispatchTool, shouldAlert, type DispatchContext } from "../registry";

const high = { category: "security", title: "RLS missing on matches", body: "b", evidence: "db_read", priority: "high" };

beforeEach(() => {
  saveSuggestion.mockReset();
  notify.mockReset();
});

describe("high-priority alert requires explicit claim-guard approval (6a)", () => {
  it("shouldAlert: only guardPassed === true, notify !== false and priority high", () => {
    expect(shouldAlert("high", { guardPassed: true })).toBe(true);
    expect(shouldAlert("high", { guardPassed: true, notify: true })).toBe(true);
    expect(shouldAlert("high", { guardPassed: false })).toBe(false);
    expect(shouldAlert("high", {})).toBe(false);
    expect(shouldAlert("high", undefined)).toBe(false);
    expect(shouldAlert("high", { guardPassed: true, notify: false })).toBe(false);
    expect(shouldAlert("medium", { guardPassed: true })).toBe(false);
    expect(shouldAlert("high", { guardPassed: "true" } as unknown as DispatchContext)).toBe(false);
  });

  it("guardPassed === true alerts", async () => {
    await dispatchTool("cybersecurity", "save_suggestion", high, { guardPassed: true });
    expect(saveSuggestion).toHaveBeenCalledTimes(1);
    expect(notify).toHaveBeenCalledTimes(1);
  });

  it.each<[string, DispatchContext | undefined]>([
    ["guardPassed === false", { guardPassed: false }],
    ["missing guard approval (no context: legacy caller)", undefined],
    ["missing guard approval (context without guardPassed)", { appendix: "Generated by x/y" }],
    ["notify: false", { guardPassed: true, notify: false }],
  ])("%s is saved but never alerts", async (_label, ctx) => {
    expect(await dispatchTool("cybersecurity", "save_suggestion", high, ctx)).toBe("Saved to the owner's suggestions inbox.");
    expect(saveSuggestion).toHaveBeenCalledTimes(1);
    expect(notify).not.toHaveBeenCalled();
  });

  it("the registry validates the category too (defence in depth)", async () => {
    await dispatchTool("cybersecurity", "save_suggestion", { ...high, category: "6% of users" }, { guardPassed: true });
    expect(saveSuggestion.mock.calls[0][0].category).toBe("general");
    await dispatchTool("cybersecurity", "save_suggestion", { ...high, category: "Security" }, { guardPassed: true });
    expect(saveSuggestion.mock.calls[1][0].category).toBe("security");
  });
});
