import { describe, it, expect, vi, beforeEach } from "vitest";

const { saveSuggestion, notify, logActivity } = vi.hoisted(() => ({ saveSuggestion: vi.fn(), notify: vi.fn(), logActivity: vi.fn() }));
vi.mock("../../lib/suggestions", () => ({ saveSuggestion: (...a: unknown[]) => saveSuggestion(...a) }));
vi.mock("../../lib/notify", () => ({ notify: (...a: unknown[]) => notify(...a) }));
vi.mock("../../lib/memory", () => ({ logActivity: (...a: unknown[]) => logActivity(...a) }));
vi.mock("../../lib/supabase", () => ({ supabaseAdmin: {} }));

import { dispatchTool, shouldAlert, type DispatchContext } from "../registry";
import { case1 } from "../../lib/__tests__/finding-fixtures";

// 7b: a high-priority finding alerts only when the evidence gate verified it as
// a bug AND the claim guard verified every figure (6a rule unchanged).
const highBug = () => {
  const c = case1();
  return { ...c, input: { ...c.input, priority: "high" } };
};
const findingCtx = (c: ReturnType<typeof case1>, extra: DispatchContext = {}): DispatchContext => ({ ...extra, finding: { run: c.run, title: String(c.input.title), body: "b" } });

beforeEach(() => {
  saveSuggestion.mockReset();
  notify.mockReset();
  logActivity.mockReset();
});

describe("high-priority alert requires explicit claim-guard approval (6a) and a gate-verified bug (7b)", () => {
  it("shouldAlert: only guardPassed === true, notify !== false and priority high", () => {
    expect(shouldAlert("high", { guardPassed: true })).toBe(true);
    expect(shouldAlert("high", { guardPassed: true, notify: true })).toBe(true);
    expect(shouldAlert("high", { guardPassed: false })).toBe(false);
    expect(shouldAlert("high", {})).toBe(false);
    expect(shouldAlert("high", undefined)).toBe(false);
    expect(shouldAlert("high", { guardPassed: true, notify: false })).toBe(false);
    expect(shouldAlert("medium", { guardPassed: true })).toBe(false);
    expect(shouldAlert("high", { guardPassed: "true" } as unknown as DispatchContext)).toBe(false);
  });

  it("a gate-verified high-priority bug with guardPassed === true alerts", async () => {
    const c = highBug();
    await dispatchTool("uxdesign", "save_suggestion", c.input, findingCtx(c, { guardPassed: true }));
    expect(saveSuggestion).toHaveBeenCalledTimes(1);
    expect(saveSuggestion.mock.calls[0][0]).toMatchObject({ category: "bug", priority: "high" });
    expect(notify).toHaveBeenCalledTimes(1);
    expect(notify.mock.calls[0][0]).toMatch(/flagged \(high\): \[Verified bug\] Leaderboard empty-state hint/);
  });

  it.each<[string, DispatchContext]>([
    ["guardPassed === false", { guardPassed: false }],
    ["context without guardPassed", { appendix: "Generated by x/y" }],
    ["notify: false", { guardPassed: true, notify: false }],
  ])("%s: the verified bug is saved but never alerts", async (_label, extra) => {
    const c = highBug();
    expect(await dispatchTool("uxdesign", "save_suggestion", c.input, findingCtx(c, extra))).toMatch(/^Saved to the owner's suggestions inbox as a VERIFIED BUG/);
    expect(saveSuggestion).toHaveBeenCalledTimes(1);
    expect(notify).not.toHaveBeenCalled();
  });

  it("a high-priority risk (downgraded bug) is saved at medium and never alerts, even fully guard-verified", async () => {
    const c = highBug();
    await dispatchTool("uxdesign", "save_suggestion", { ...c.input, what_checked_to_disprove: "" }, findingCtx(c, { guardPassed: true }));
    expect(saveSuggestion.mock.calls[0][0]).toMatchObject({ category: "risk", priority: "medium" });
    expect(saveSuggestion.mock.calls[0][0].title).toMatch(/^\[Risk\] /);
    expect(notify).not.toHaveBeenCalled();
  });

  it("a high-priority product idea is saved as a low-priority idea and never alerts", async () => {
    const c = highBug();
    await dispatchTool("uxdesign", "save_suggestion", { ...c.input, class: "product_idea", category: "security" }, findingCtx(c, { guardPassed: true }));
    expect(saveSuggestion.mock.calls[0][0]).toMatchObject({ category: "idea", priority: "low" });
    expect(saveSuggestion.mock.calls[0][0].title).toMatch(/^\[Idea\] /);
    expect(notify).not.toHaveBeenCalled();
  });

  it("a legacy caller without run context saves nothing and never alerts", async () => {
    const c = highBug();
    expect(await dispatchTool("uxdesign", "save_suggestion", c.input, { guardPassed: true })).toMatch(/^Not saved: findings can only be submitted from an investigation run/);
    expect(await dispatchTool("uxdesign", "save_suggestion", c.input)).toMatch(/^Not saved/);
    expect(saveSuggestion).not.toHaveBeenCalled();
    expect(notify).not.toHaveBeenCalled();
  });

  it("the old free-form contract (category/title/body/evidence) is rejected by the gate", async () => {
    const c = case1();
    const out = await dispatchTool("cybersecurity", "save_suggestion", { category: "security", title: "RLS missing on matches", body: "b", evidence: "db_read", priority: "high" }, findingCtx(c, { guardPassed: true }));
    expect(out).toMatch(/^Not saved — rejected by the evidence gate \(invalid_input\)/);
    expect(saveSuggestion).not.toHaveBeenCalled();
    expect(notify).not.toHaveBeenCalled();
  });
});
